function kiks_arena_new
global KIKS_ARENA_DEFAULT_COLOR;

h = dialog('Visible','off');

set(h,'Name','New arena');
p=get(h,'Position');
xs=300;
ys=150;
p(1)=p(1)+(p(3)-xs)/2;
p(2)=p(2)+(p(4)-ys)/2;
p(3)=xs;
p(4)=ys;
set(h,'Position',p);

h1 = uicontrol('Parent',h, ...
    'FontName','verdana', ...
    'ListboxTop',0, ...
    'Position',[40 120 100 18], ...
    'HorizontalAlignment','right', ...
    'String','width (in mm)', ...
    'Style','text', ...
    'Tag','StaticText');
h1 = uicontrol('Parent',h, ...
    'BackgroundColor',[1 1 1], ...
    'Units','pixels', ...
    'FontUnits','points', ...
    'FontName','Courier New', ...
    'FontSize',9, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','left', ...
    'Position',[150 120 100 20], ...
    'Style','edit', ...
    'String','', ...
    'Tag','width');

h1 = uicontrol('Parent',h, ...
    'FontName','verdana', ...
    'ListboxTop',0, ...
    'Position',[40 90 100 18], ...
    'HorizontalAlignment','right', ...
    'String','height (in mm)', ...
    'Style','text', ...
    'Tag','StaticText');
h1 = uicontrol('Parent',h, ...
    'BackgroundColor',[1 1 1], ...
    'Units','pixels', ...
    'FontUnits','points', ...
    'FontName','Courier New', ...
    'FontSize',9, ...
    'FontWeight','normal', ...
    'HorizontalAlignment','left', ...
    'Position',[150 90 100 20], ...
    'Style','edit', ...
    'String','', ...
    'Tag','height');

h1 = uicontrol('Parent',h, ...
    'FontName','verdana', ...
    'ListboxTop',0, ...
    'Position',[40 60 100 18], ...
    'HorizontalAlignment','right', ...
    'String','wall color', ...
    'Style','text', ...
    'Tag','StaticText');
h1 = uicontrol('Parent',h, ...
    'BackgroundColor',[KIKS_ARENA_DEFAULT_COLOR/255 KIKS_ARENA_DEFAULT_COLOR/255 KIKS_ARENA_DEFAULT_COLOR/255], ...
    'Callback','v=get(gco,''Value''); set(gco,''BackgroundColor'',[v/255 v/255 v/255])', ...
    'Enable','on', ...
    'ListboxTop',0, ...
    'Max',255, ...
    'Min',1, ...
    'Position',[150 60 100 20], ...
    'Style','slider', ...
    'Tag','color', ...
    'Value',KIKS_ARENA_DEFAULT_COLOR, ...
    'Visible','on');


h1 = uicontrol('Parent',h, ...
    'Units','pixels', ...
    'FontWeight','normal', ...
    'HorizontalAlignment','left', ...
    'Position',[100 30 100 20], ...
    'Style','checkbox', ...
    'String','rounded corners', ...
    'Tag','rounded');


h3 = uicontrol('Parent',h, ...
    'Callback','kiks_arena_new_create;', ...
    'Enable','on', ...
    'ListboxTop',0, ...
    'Position',[5 5 71 20], ...
    'String','OK', ...
    'Tag','btn_OK');

h4 = uicontrol('Parent',h, ...
    'Callback','close(gcbf);', ...
    'Enable','on', ...
    'ListboxTop',0, ...
    'Position',[224 5 71 20], ...
    'String','Cancel', ...
    'Tag','btn_cancel');

set(h,'Visible','on');