function kiks_gui_kiksnet_password(title)

h=dialog('Visible','off','PaperUnits','points');
set(h,'Name',title);
p=get(h,'Position');
xs=300;
ys=100;
p(1)=p(1)+(p(3)-xs)/2;
p(2)=p(2)+(p(4)-ys)/2;
p(3)=xs;
p(4)=ys;
set(h,'Position',p);

h1 = uicontrol('Parent',h, ...
    'FontName','verdana', ...
    'BackgroundColor',[1 1 1], ...
    'HorizontalAlignment','left', ...
    'ListboxTop',0, ...
    'Position',[50 50 200 18], ...
    'String','', ...
    'Style','edit', ...
    'Tag','passwd', ...
    'TooltipString','Enter administrator password for KiKSnet server');

h2 = uicontrol('Parent',h, ...
    'Callback','kiks_gui_kiksnet_password_close(gcf);', ...
    'ListboxTop',0, ...
    'Position',[100 10 100 20], ...
    'String','ok', ...
    'Tag','ok');
set(h,'Visible','on');

uiwait(h);